/*
  # Create portfolio_snapshots table

  1. New Tables
    - `portfolio_snapshots`
      - `id` (uuid, primary key)
      - `created_at` (timestamptz, auto-set)
      - `portfolio_value` (numeric) — total portfolio value in dollars
      - `portfolio_risk_pct` (numeric) — current risk as % of portfolio
      - `num_positions` (int) — number of active positions
      - `market_regime` (text) — current regime label (e.g. 'neutral', 'trending')

  2. Security
    - Enable RLS on `portfolio_snapshots`
    - Public read access (read-only dashboard data, no PII)
    - Authenticated insert only (dashboard can persist snapshots)

  3. Notes
    - Stores each 15-minute snapshot generated by the ML/DL ensemble engine
    - Used for the P&L evolution chart history
*/

CREATE TABLE IF NOT EXISTS portfolio_snapshots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  timestamp timestamptz DEFAULT now(),
  portfolio_value numeric(14, 2) NOT NULL DEFAULT 100000.00,
  portfolio_risk_pct numeric(6, 4) DEFAULT 0,
  num_positions integer DEFAULT 0,
  market_regime text DEFAULT 'neutral'
);

ALTER TABLE portfolio_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read portfolio snapshots"
  ON portfolio_snapshots
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can insert portfolio snapshots"
  ON portfolio_snapshots
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_timestamp
  ON portfolio_snapshots (timestamp DESC);
